### ISSUE TITLE
Patches to Tracking Pipeline

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/Tracking#25]
This issue will be used to keep track of the updates that need to be made to the tracking pipeline. 

- [x] Update the python configs to include reasonable defaults for all variables and avoid hard coded paths.
- [x] All classes need to be fully documented.
- [x] Move monitoring histograms to separate processor and use internal histogram booking.
- [x] Update README
- [x] Use logger instead of debug flag.

**Comment by pbutti** [comment]
The README update is in a separate PR

**Comment by pbutti** [comment]
Can this be closed? @omar-moreno
